# -*- coding: utf-8 -*-
"""Generates the UI asset files used by the app theme.

  src/ui/uiicons_data.inc   stroke icon path data (24x24 grid) that is #included by uiicons.cpp
  resources/theme/*.png     small chevron / check images referenced from the QSS

Run from the repository root:   python tools/gen_ui_assets.py
Requires Pillow. The icon shapes live in tools/ui_icons.json.
"""
import json
import os

from PIL import Image, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def write_inc():
    with open(os.path.join(ROOT, "tools", "ui_icons.json"), encoding="utf-8") as f:
        icons = json.load(f)
    out = os.path.join(ROOT, "src", "ui", "uiicons_data.inc")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Generated by tools/gen_ui_assets.py - do not edit by hand.\n")
        for name, body in icons.items():
            f.write('{"%s", R"SVG(%s)SVG"},\n' % (name, body))
    return len(icons)


def _finish(im, size):
    return im.resize((size, size), Image.LANCZOS)


def chevron(direction, color, size=24, ss=8):
    s = size * ss
    im = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    w = int(2.2 * ss)
    c = s / 2
    a = 4.2 * ss
    if direction == "down":
        pts = [(c - a, c - a / 2), (c, c + a / 2), (c + a, c - a / 2)]
    elif direction == "up":
        pts = [(c - a, c + a / 2), (c, c - a / 2), (c + a, c + a / 2)]
    elif direction == "right":
        pts = [(c - a / 2, c - a), (c + a / 2, c), (c - a / 2, c + a)]
    else:
        pts = [(c + a / 2, c - a), (c - a / 2, c), (c + a / 2, c + a)]
    d.line(pts, fill=color, width=w, joint="curve")
    for p in (pts[0], pts[-1]):
        d.ellipse([p[0] - w / 2, p[1] - w / 2, p[0] + w / 2, p[1] + w / 2], fill=color)
    return _finish(im, size)


def check(color, size=24, ss=8):
    s = size * ss
    im = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    w = int(2.6 * ss)
    pts = [(s * 0.24, s * 0.53), (s * 0.43, s * 0.71), (s * 0.77, s * 0.32)]
    d.line(pts, fill=color, width=w, joint="curve")
    for p in (pts[0], pts[-1]):
        d.ellipse([p[0] - w / 2, p[1] - w / 2, p[0] + w / 2, p[1] + w / 2], fill=color)
    return _finish(im, size)


def write_pngs():
    out = os.path.join(ROOT, "resources", "theme")
    os.makedirs(out, exist_ok=True)
    for mode, col in (("light", "#5B6E7C"), ("dark", "#8496A4")):
        for direction in ("down", "up", "right", "left"):
            chevron(direction, col).save(os.path.join(out, "chev-%s-%s.png" % (direction, mode)))
    check("#FFFFFF").save(os.path.join(out, "check-white.png"))


if __name__ == "__main__":
    n = write_inc()
    write_pngs()
    print("ok: %d icons, chevron/check images written" % n)
